const faker = {
  name: {
    firstName() {
      // array containing 100 random first names
      const firstNames = [
        'Tim',
        'John',
        'Jane',
        'Jack',
        'Jill',
        'Alan',
        'Mary',
        'Mavis',
        'Mildred',
        'Mortimer',
        'Morticia',
        'Fred',
        'Freda',
        'Tom',
        'Tina',
        'Terry',
        'Trevor',
        'Trevi',
        'Lili',
        'Lola',
        'Lily',
        'Fred',
        'Fox',
        'Ken',
        'Kenny',
        'Kendra',
        'Kendrick',
      ];
      return firstNames[Math.floor(Math.random() * firstNames.length)];
    },
    lastName() {
      // array containing 100 random last names
      const lastNames = [
        'Smith',
        'Johnson',
        'Williams',
        'Jones',
        'Brown',
        'Davis',
        'Miller',
        'Wilson',
        'Moore',
        'Taylor',
        'Anderson',
        'Thomas',
        'Jackson',
        'White',
        'Harris',
        'Martin',
        'Thompson',
        'Garcia',
        'Martinez',
        'Robinson',
        'Clark',
        'Rodriguez',
        'Lewis',
        'Lee',
        'Walker',
        'Hall',
        'Allen',
        'Young',
        'Hernandez',
        'King',
        'Wright',
        'Lopez',
        'Hill',
        'Scott',
        'Green',
        'Adams',
        'Baker',
        'Gonzalez',
        'Nelson',
        'Carter',
        'Mitchell',
        'Perez',
        'Roberts',
        'Turner',
        'Phillips',
        'Campbell',
        'Parker',
        'Evans',
        'Edwards',
        'Collins',
        'Stewart',
        'Sanchez',
        'Morris',
        'Rogers',
        'Reed',
        'Cook',
        'Morgan',
        'Bell',
        'Murphy',
        'Bailey',
        'Rivera',
        'Cooper',
        'Richardson',
        'Cox',
        'Howard',
        'Ward',
        'Torres',
        'Peterson',
        'Gray',
        'Ramirez',
        'James',
        'Watson',
        'Brooks',
        'Kelly',
        'Sanders',
        'Price',
        'Bennett',
        'Wood',
        'Barnes',
        'Ross',
        'Henderson',
        'Coleman',
        'Jenkins',
        'Perry',
        'Powell',
        'Long',
        'Patterson',
        'Hughes',
        'Flores',
        'Washington',
        'Butler',
        'Simmons',
        'Foster',
        'Gonzales',
        'Bryant',
        'Alexander',
        'Russell',
        'Griffin',
        'Diaz',
        'Hayes',
      ];

      return lastNames[Math.floor(Math.random() * lastNames.length)];
    },
  },
  date: {
    past() {
      const date = new Date();
      date.setDate(date.getDate() - Math.floor(Math.random() * 100));
      // return date in YYYY-MM-DD format
      return date.toISOString().split('T')[0];
    },
  },
  time: {
    past() {
      const hour = Math.round(Math.random() * 24);
      const minute = Math.round(Math.random() * 60);
      return `${String(hour).padStart(2, 0)}:${String(minute).padStart(2, 0)}`;
    },
  },
  employee: {
    id() {
      return `EMP${Math.floor(Math.random() * 10000)}`;
    },
  },
};

export default faker;
